#!/bin/sh 
tmux new-session -d 'cd ng-src && npm start'
tmux split-window -v 'cd hoodie-src && npm start'
tmux split-window -h 'nginx -c $PWD/nginx.conf'
#tmux new-window 'mutt'
tmux -2 attach-session -d 
