version: "3.3"

services:
    couch:
        image: couchdb
        restart: always
        #ports:
        #    - "35984:5984"
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=${COUCH_PW}
        volumes:
            - couch-data:/opt/couchdb/data/
    hoodie:
        image: cborgolte/shopping-list
        restart: always
        #ports:
        #    - "8081:8080"
        depends_on:
            - couch
        environment:
            - hoodie_adminPassword=${COUCH_PW}
            - hoodie_dbUrl=http://admin:${COUCH_PW}@couch:5984/
            - hoodie_inMemory=true
            - hoodie_public=/app/public
    caddy:
        image: abiosoft/caddy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            -   ./caddy/Caddyfile:/etc/Caddyfile
            -   ./caddy/.caddy:/root/.caddy
        depends_on:
            - couch
            - hoodie
volumes:
    couch-data:
